# Generated by Django 4.2.2 on 2023-06-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=50)),
                ('techskills', models.CharField(choices=[('PYTHON', 'Python'), ('RUBY', 'Ruby'), ('JAVA', 'Java'), ('DOCKER', 'Docker'), ('NODE', 'Node'), ('JAVASCRIPT', 'JavaScript')], max_length=20)),
            ],
        ),
    ]
