# Generated by Django 4.2.2 on 2023-06-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='multi_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
