# Generated by Django 4.2.2 on 2023-06-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revapi', '0002_candidate_multi_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='multi_info',
        ),
    ]
