# Generated by Django 4.2.2 on 2023-06-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revapi', '0003_remove_candidate_multi_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiCandidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi_candidates', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('name', 'address', 'number', 'email', 'location', 'techskills')},
        ),
    ]
