# Generated by Django 4.2.2 on 2023-06-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revapi', '0004_multicandidates_alter_candidate_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together=set(),
        ),
    ]
