# Generated by Django 4.2.2 on 2023-06-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revapi', '0005_alter_candidate_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='techskills',
        ),
        migrations.AddField(
            model_name='candidate',
            name='TECH_SKILLS',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
